### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Redskyer** [rtuszik/photon-docker#81]
**Describe the bug**
A few days ago, I decided to try using Photon, but until now I don't get it to work. At first I had that error:
https://github.com/rtuszik/photon-docker/issues/74
But now I get another error and I don't know why. I always downloaded about 100GB data, but for testing I tried to set the Country Code.

**To Reproduce**
I tried to use diefferent Base URLs:
BASE_URL=https://download1.graphhopper.com/public/experimental
BASE_URL=https://download1.graphhopper.com/public
BASE_URL=https://r2.koalasec.org/public

But I'm getting always the same error. I've also deleted the container and volume, but no success.

```
### **`photon-docker` configuration:**
   photon:
     container_name: Dawarich_Photon
     image: rtuszik/photon-docker:latest
     environment:
        - UPDATE_STRATEGY=PARALLEL
        - UPDATE_INTERVAL=24h
        - BASE_URL=https://download1.graphhopper.com/public/       # Official Server
        - COUNTRY_CODE=de
#        - BASE_URL=https://r2.koalasec.org/public                   # Community Server
     volumes:
        - dawarich_photon_data:/photon/photon_data
     restart: unless-stopped
```

### System Info
 - **Host OS: Unraid 7.1.3** 
 - **Host Type: Docker**
 - **Hardware details:**
   - **CPU:Intel® Core™ i7-4770 CPU**
   - **Available RAM:32 GiB DDR3** 
   - **Storage Type:SATA SSD**
   - **Storage Size:2TB**

**Debug Logs**
/photon/photon_data  99%[==================> ]   9.13G  1.57MB/s    eta 1s
/photon/photon_data 100%[===================>]   9.13G  1.57MB/s    in 85m 6s
2025-06-16 20:07:16 (1.83 MB/s) - ‘/photon/photon_data/temp/photon-db.tar.bz2’ saved [9805188788/9805188788]
photon-db.tar.bz2: OK
[INFO] 2025-06-16 20:07:42 - MD5 verification successful
[INFO] 2025-06-16 20:07:42 - Extracting archive, this may take some time...
[INFO] 2025-06-16 20:07:42 - Extracting archive to /photon/photon_data/temp
[INFO] 2025-06-16 20:11:41 - Extraction completed successfully
[INFO] 2025-06-16 20:11:41 - Moving index from /photon/photon_data/temp to /photon/photon_data/node_1
[INFO] 2025-06-16 20:11:41 - Searching for opensearch directory in: /photon/photon_data/temp
[INFO] 2025-06-16 20:11:41 - Found opensearch candidates:
[ERROR] 2025-06-16 20:11:41 - Could not find opensearch directory in extracted files
[ERROR] 2025-06-16 20:11:41 - Failed to move index
[INFO] 2025-06-16 20:11:41 - Cleaning up temporary directory
[INFO] 2025-06-16 20:11:43 - Final photon_data directory structure:
/photon/photon_data
0 directories, 0 files
[ERROR] 2025-06-16 20:11:43 - Failed to setup initial index
[INFO] 2025-06-16 20:11:50 - Environment variables:
[INFO] 2025-06-16 20:11:50 - UPDATE_STRATEGY=PARALLEL
[INFO] 2025-06-16 20:11:50 - UPDATE_INTERVAL=24h
[INFO] 2025-06-16 20:11:50 - LOG_LEVEL=INFO
[INFO] 2025-06-16 20:11:50 - BASE_URL=https://download1.graphhopper.com/public
[INFO] 2025-06-16 20:11:50 - FORCE_UPDATE=FALSE
[INFO] 2025-06-16 20:11:50 - SKIP_MD5_CHECK=FALSE
[INFO] 2025-06-16 20:11:50 - COUNTRY_CODE=de
[INFO] 2025-06-16 20:11:50 - FILE_URL=
[INFO] 2025-06-16 20:11:50 - No opensearch index found, performing initial download
[INFO] 2025-06-16 20:11:50 - Starting sequential update process
[INFO] 2025-06-16 20:11:50 - Stopping Photon service before update
[INFO] 2025-06-16 20:11:52 - Downloading new index
[INFO] 2025-06-16 20:11:53 - Sufficient disk space available. Required: 9805188788B, Available: 1234031484928B
[INFO] 2025-06-16 20:11:53 - Downloading index from https://download1.graphhopper.com/public/extracts/by-country-code/de/photon-db-de-latest.tar.bz2
--2025-06-16 20:11:53--  https://download1.graphhopper.com/public/extracts/by-country-code/de/photon-db-de-latest.tar.bz2
Resolving download1.graphhopper.com (download1.graphhopper.com)... 135.181.163.222
Connecting to download1.graphhopper.com (download1.graphhopper.com)|135.181.163.222|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9805188788 (9.1G) [application/octet-stream]
Saving to: ‘/photon/photon_data/temp/photon-db.tar.bz2’
/photon/photon_data   0%[                    ]       0  --.-KB/s
/photon/photon_data   0%[                    ] 319.74K  1.52MB/s

I know that this isn't a debug log, but maybe it can help. If not, I would do it again with debug log.

Edit: added [Debug Log](https://github.com/user-attachments/files/20772693/Debug.txt)
